import { Router } from 'express';
import { adminCourses, adminHskOverview, adminLessonContent, adminLessons, adminNotifications, adminUsers, broadcastNotification, createContentBlock, createCourse, createLesson, createModule, deleteContentBlock, deleteLesson, deleteModule, moveContentBlock, summary, updateContentBlock, updateCourse, updateLesson, updateModule, updateUserRole, updateUserStatus } from '../controllers/admin.controller.js';
import { requireAuth, requireRole } from '../middleware/auth.js';
import { asyncHandler } from '../utils/http.js';

export const adminRouter = Router();
adminRouter.use(requireAuth, requireRole('admin'));
adminRouter.get('/summary', asyncHandler(summary));
adminRouter.get('/users', asyncHandler(adminUsers));
adminRouter.patch('/users/:id/status', asyncHandler(updateUserStatus));
adminRouter.patch('/users/:id/role', asyncHandler(updateUserRole));
adminRouter.get('/courses', asyncHandler(adminCourses));
adminRouter.post('/courses', asyncHandler(createCourse));
adminRouter.patch('/courses/:id', asyncHandler(updateCourse));
adminRouter.post('/courses/:courseId/modules', asyncHandler(createModule));
adminRouter.patch('/modules/:id', asyncHandler(updateModule));
adminRouter.delete('/modules/:id', asyncHandler(deleteModule));
adminRouter.get('/lessons', asyncHandler(adminLessons));
adminRouter.get('/lessons/:id/content', asyncHandler(adminLessonContent));
adminRouter.post('/modules/:moduleId/lessons', asyncHandler(createLesson));
adminRouter.patch('/lessons/:id', asyncHandler(updateLesson));
adminRouter.delete('/lessons/:id', asyncHandler(deleteLesson));
adminRouter.post('/lessons/:lessonId/content-blocks', asyncHandler(createContentBlock));
adminRouter.patch('/content-blocks/:id', asyncHandler(updateContentBlock));
adminRouter.delete('/content-blocks/:id', asyncHandler(deleteContentBlock));
adminRouter.post('/content-blocks/:id/move', asyncHandler(moveContentBlock));
adminRouter.get('/hsk', asyncHandler(adminHskOverview));
adminRouter.get('/notifications', asyncHandler(adminNotifications));
adminRouter.post('/notifications/broadcast', asyncHandler(broadcastNotification));
