import { useState } from 'react';
import { ArrowLeft, ArrowRight, Check, Eye, EyeOff, LockKeyhole, Mail, UserRound } from 'lucide-react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { zodResolver } from '@hookform/resolvers/zod';
import { apiPost } from '../api/client';
import { Brand } from '../components/brand';
import { Button } from '../components/ui';
import { useAuthStore } from '../stores/auth.store';
import type { User } from '../types';

const loginSchema = z.object({ email: z.string().email('Nhập email hợp lệ.'), password: z.string().min(1, 'Nhập mật khẩu của bạn.') });
const registerSchema = z.object({ name: z.string().min(2, 'Tên cần có ít nhất 2 ký tự.'), email: z.string().email('Nhập email hợp lệ.'), password: z.string().min(8, 'Mật khẩu cần ít nhất 8 ký tự.'), agree: z.literal(true, { errorMap: () => ({ message: 'Bạn cần đồng ý với điều khoản.' }) }) });
type LoginForm = z.infer<typeof loginSchema>;
type RegisterForm = z.infer<typeof registerSchema>;

export function AuthLayout({ children, mode: _mode }: { children: React.ReactNode; mode: 'login' | 'register' | 'forgot' }) { return <div className="auth-page"><div className="auth-aside"><Brand /><div className="auth-aside-content"><span className="eyebrow eyebrow-light">HỌC THEO CÁCH CỦA BẠN</span><h1>Thêm một ngôn ngữ.<br /><em>Mở thêm một thế giới.</em></h1><p>Những bài học nhỏ, lộ trình rõ ràng và cảm giác tiến bộ mỗi ngày.</p><div className="auth-quote"><span className="quote-mark">“</span><p>Học tiếng Trung không khó. Khó là tìm được cách học phù hợp với bạn.</p><small>— HanLearn</small></div></div><div className="auth-aside-footer"><span>◎</span> Được thiết kế cho người Việt học tiếng Trung</div></div><main className="auth-main"><div className="auth-mobile-brand"><Brand /></div><div className="auth-box">{children}</div><span className="auth-copyright">© 2025 HanLearn · <Link to="/">Trang chủ</Link></span></main></div>; }

export function LoginPage() {
  const navigate = useNavigate(); const location = useLocation(); const setSession = useAuthStore((state) => state.setSession); const [showPassword, setShowPassword] = useState(false); const [serverError, setServerError] = useState('');
  const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<LoginForm>({ resolver: zodResolver(loginSchema) });
  async function onSubmit(values: LoginForm) { setServerError(''); try { const response = await apiPost<{ accessToken: string; user: User }>('/auth/login', values); setSession(response.accessToken, response.user); const next = new URLSearchParams(location.search).get('next') ?? '/dashboard'; navigate(next); } catch (error) { setServerError(getApiError(error)); } }
  return <AuthLayout mode="login"><div className="auth-heading"><span className="eyebrow">CHÀO MỪNG TRỞ LẠI</span><h1>Đăng nhập để tiếp tục</h1><p>Tiếp tục hành trình chinh phục tiếng Trung của bạn.</p></div><form className="auth-form" onSubmit={handleSubmit(onSubmit)}>{serverError && <div className="form-error-banner">{serverError}</div>}<label>Email<input {...register('email')} type="email" placeholder="you@example.com" autoComplete="email" />{errors.email && <small>{errors.email.message}</small>}</label><label>Mật khẩu<div className="password-field"><input {...register('password')} type={showPassword ? 'text' : 'password'} placeholder="Nhập mật khẩu" autoComplete="current-password" /><button type="button" aria-label={showPassword ? 'Ẩn mật khẩu' : 'Hiện mật khẩu'} onClick={() => setShowPassword(!showPassword)}>{showPassword ? <EyeOff size={17} /> : <Eye size={17} />}</button></div>{errors.password && <small>{errors.password.message}</small>}</label><div className="form-row"><label className="checkbox-label"><input type="checkbox" /> <span>Ghi nhớ đăng nhập</span></label><Link to="/forgot-password">Quên mật khẩu?</Link></div><Button type="submit" className="full-width" size="lg" loading={isSubmitting}>Đăng nhập <ArrowRight size={17} /></Button></form><div className="auth-divider"><span>hoặc</span></div><button className="social-button" type="button"><span className="google-mark">G</span> Tiếp tục với Google</button><p className="auth-switch">Chưa có tài khoản? <Link to="/register">Đăng ký miễn phí</Link></p></AuthLayout>;
}

export function RegisterPage() {
  const navigate = useNavigate(); const setSession = useAuthStore((state) => state.setSession); const [showPassword, setShowPassword] = useState(false); const [serverError, setServerError] = useState('');
  const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<RegisterForm>({ resolver: zodResolver(registerSchema), defaultValues: { agree: true } });
  async function onSubmit(values: RegisterForm) { setServerError(''); try { const response = await apiPost<{ accessToken: string; user: User }>('/auth/register', values); setSession(response.accessToken, response.user); navigate('/dashboard'); } catch (error) { setServerError(getApiError(error)); } }
  return <AuthLayout mode="register"><Link to="/" className="back-link"><ArrowLeft size={15} /> Trang chủ</Link><div className="auth-heading"><span className="eyebrow">BẮT ĐẦU HÀNH TRÌNH</span><h1>Tạo tài khoản HanLearn</h1><p>Học miễn phí, lưu tiến độ và xây dựng thói quen học đều.</p></div><form className="auth-form" onSubmit={handleSubmit(onSubmit)}>{serverError && <div className="form-error-banner">{serverError}</div>}<label>Họ và tên<div className="input-with-icon"><UserRound size={17} /><input {...register('name')} placeholder="Nguyễn Văn A" autoComplete="name" /></div>{errors.name && <small>{errors.name.message}</small>}</label><label>Email<div className="input-with-icon"><Mail size={17} /><input {...register('email')} type="email" placeholder="you@example.com" autoComplete="email" /></div>{errors.email && <small>{errors.email.message}</small>}</label><label>Mật khẩu<div className="password-field"><LockKeyhole size={17} className="password-icon" /><input {...register('password')} type={showPassword ? 'text' : 'password'} placeholder="Ít nhất 8 ký tự" autoComplete="new-password" /><button type="button" aria-label={showPassword ? 'Ẩn mật khẩu' : 'Hiện mật khẩu'} onClick={() => setShowPassword(!showPassword)}>{showPassword ? <EyeOff size={17} /> : <Eye size={17} />}</button></div>{errors.password && <small>{errors.password.message}</small>}</label><label className="checkbox-label"><input {...register('agree')} type="checkbox" /><span>Tôi đồng ý với <a href="#terms">Điều khoản sử dụng</a> và <a href="#privacy">Chính sách riêng tư</a>.</span></label>{errors.agree && <small className="standalone-error">{errors.agree.message}</small>}<Button type="submit" className="full-width" size="lg" loading={isSubmitting}>Tạo tài khoản <ArrowRight size={17} /></Button></form><p className="auth-switch">Đã có tài khoản? <Link to="/login">Đăng nhập</Link></p></AuthLayout>;
}

export function ForgotPasswordPage() { const [sent, setSent] = useState(false); const { register, handleSubmit, formState: { isSubmitting } } = useForm<{ email: string }>({ resolver: zodResolver(z.object({ email: z.string().email('Nhập email hợp lệ.') })) }); return <AuthLayout mode="forgot"><Link to="/login" className="back-link"><ArrowLeft size={15} /> Quay lại đăng nhập</Link>{sent ? <div className="success-panel"><span className="success-icon"><Check size={24} /></span><h1>Kiểm tra email của bạn</h1><p>Nếu tài khoản tồn tại, chúng tôi đã gửi hướng dẫn đặt lại mật khẩu.</p><Link className="button button-primary button-md" to="/login">Quay lại đăng nhập</Link></div> : <><div className="auth-heading"><span className="eyebrow">KHÔI PHỤC TÀI KHOẢN</span><h1>Quên mật khẩu?</h1><p>Nhập email bạn đã đăng ký, chúng tôi sẽ gửi đường dẫn khôi phục.</p></div><form className="auth-form" onSubmit={handleSubmit(async () => { await new Promise((resolve) => setTimeout(resolve, 500)); setSent(true); })}><label>Email đăng ký<input {...register('email')} type="email" placeholder="you@example.com" /></label><Button type="submit" className="full-width" size="lg" loading={isSubmitting}>Gửi hướng dẫn <ArrowRight size={17} /></Button></form></>}</AuthLayout>; }

function getApiError(error: unknown) { if (typeof error === 'object' && error && 'response' in error) { const response = (error as { response?: { data?: { message?: string } } }).response; return response?.data?.message ?? 'Không thể hoàn tất yêu cầu.'; } return 'Không thể kết nối tới máy chủ. Hãy thử lại.'; }
