import { ArrowRight, Check, Headphones, Mic2, PenLine, Play, Sparkles, BookOpen, Flame, Quote } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Brand } from '../components/brand';
import { PublicHeader } from '../components/layout';
import { Badge, Card, SectionHeading } from '../components/ui';

const skills = [
  { icon: Headphones, title: 'Nghe chủ động', description: 'Bắt nhịp thanh điệu qua hội thoại đời thường, tốc độ điều chỉnh theo trình độ.', accent: 'red', tag: 'Listening' },
  { icon: Mic2, title: 'Nói tự tin', description: 'Luyện phát âm từng từ, từng câu với phản hồi rõ ràng và dễ áp dụng.', accent: 'orange', tag: 'Speaking' },
  { icon: BookOpen, title: 'Đọc hiểu sâu', description: 'Đọc đoạn văn có pinyin, bản dịch và tra cứu từ ngay trong ngữ cảnh.', accent: 'purple', tag: 'Reading' },
  { icon: PenLine, title: 'Viết đúng nét', description: 'Nhớ mặt chữ và thứ tự nét bằng bài tập ngắn, trực quan, dễ lặp lại.', accent: 'green', tag: 'Writing' },
];

const courses = [
  { title: 'Chinese Foundation', subtitle: 'Nền tảng giao tiếp', level: 'HSK 1', lessons: '24 bài', color: '#E53935', icon: '你好' },
  { title: 'HSK 1 Core', subtitle: 'Từ vựng thiết yếu', level: 'HSK 1', lessons: '36 bài', color: '#F97316', icon: '学习' },
  { title: 'HSK 2 Conversation', subtitle: 'Nói tự nhiên hơn', level: 'HSK 2', lessons: '42 bài', color: '#8B5CF6', icon: '对话' },
];

export function LandingPage() {
  return <div className="landing-page"><PublicHeader /><main>
    <section className="landing-hero"><div className="hero-copy"><Badge tone="red"><Sparkles size={13} /> Học thông minh, tiến bộ bền vững</Badge><h1>Học tiếng Trung<br /><span>dễ dàng hơn mỗi ngày</span></h1><p>Luyện Nghe – Nói – Đọc – Viết theo lộ trình cá nhân hóa. Mỗi bài học nhỏ là một bước tiến gần hơn đến mục tiêu của bạn.</p><div className="hero-actions"><Link className="button button-primary button-lg" to="/register">Bắt đầu học miễn phí <ArrowRight size={18} /></Link><Link className="button button-secondary button-lg" to="/courses"><Play size={16} fill="currentColor" /> Khám phá khóa học</Link></div><div className="hero-trust"><div className="avatar-stack"><span>AN</span><span>ML</span><span>QK</span><span>+</span></div><span><strong>12.000+</strong> người học đang tiến bộ mỗi ngày</span></div></div><div className="hero-visual"><div className="hero-orbit orbit-one" /><div className="hero-orbit orbit-two" /><div className="hero-card hero-card-main"><div className="hero-card-top"><span className="hero-card-label">BÀI HỌC HÔM NAY</span><span className="hero-card-check"><Check size={14} /></span></div><div className="hanzi-hero">你好</div><div className="hero-pinyin">nǐ hǎo</div><div className="hero-meaning">Xin chào</div><div className="hero-audio"><span className="audio-play"><Play size={12} fill="currentColor" /></span><span className="audio-wave"><i /><i /><i /><i /><i /><i /><i /><i /><i /></span><span className="audio-time">0:04</span></div><div className="hero-card-footer"><span>HSK 1 · Bài 01</span><span>+20 XP</span></div></div><div className="floating-card floating-streak"><span className="float-icon flame"><Flame size={17} fill="currentColor" /></span><div><strong>12 ngày</strong><small>Chuỗi học</small></div></div><div className="floating-card floating-progress"><div className="mini-ring"><span>82%</span></div><div><strong>Tiến bộ tốt!</strong><small>Mục tiêu tuần</small></div></div><div className="hero-character character-one">学</div><div className="hero-character character-two">习</div></div></section>

    <section className="landing-stats"><div><strong>120+</strong><span>bài học thực tế</span></div><div><strong>2.500+</strong><span>từ vựng chuẩn HSK</span></div><div><strong>4</strong><span>kỹ năng toàn diện</span></div><div><strong>12k</strong><span>người học tích cực</span></div></section>

    <section className="landing-section skills-section" id="skills"><SectionHeading eyebrow="HỌC TOÀN DIỆN" title="Mỗi kỹ năng, một cách học đúng" description="Một hệ sinh thái học tập được thiết kế để bạn không chỉ nhớ từ, mà còn dùng được tiếng Trung trong đời sống." /><div className="skill-grid">{skills.map(({ icon: Icon, title, description, accent, tag }) => <Card className={`skill-card skill-${accent}`} key={tag}><div className="skill-card-top"><span className="skill-icon"><Icon size={21} /></span><span className="skill-tag">{tag}</span></div><h3>{title}</h3><p>{description}</p><Link to={`/${tag.toLowerCase()}`} className="text-link">Khám phá <ArrowRight size={15} /></Link></Card>)}</div></section>

    <section className="landing-section roadmap-section" id="roadmap"><div className="roadmap-copy"><span className="eyebrow">LỘ TRÌNH RÕ RÀNG</span><h2>Từ “你好” đến<br /><span>tự tin giao tiếp</span></h2><p>Không còn học lan man. Mỗi cấp độ có mục tiêu cụ thể, bài học vừa sức và cột mốc để bạn nhìn thấy tiến bộ của chính mình.</p><Link className="text-link" to="/hsk">Xem lộ trình HSK <ArrowRight size={15} /></Link></div><div className="roadmap-steps"><div className="roadmap-line" />{[['01', 'HSK 1', 'Nền tảng vững chắc', '500 từ vựng'], ['02', 'HSK 2', 'Giao tiếp hàng ngày', '1.272 từ vựng'], ['03', 'HSK 3', 'Mở rộng thế giới', '2.245 từ vựng']].map(([number, level, title, meta], index) => <div className={`roadmap-step ${index === 0 ? 'current' : ''}`} key={level}><span className="step-number">{number}</span><div><div className="step-level">{level} {index === 0 && <Badge tone="red">Bắt đầu</Badge>}</div><strong>{title}</strong><small>{meta}</small></div><div className="step-arrow"><ArrowRight size={16} /></div></div>)}</div></section>

    <section className="landing-section courses-section" id="courses"><SectionHeading eyebrow="KHÓA HỌC ĐƯỢC YÊU THÍCH" title="Bắt đầu đúng nơi bạn cần" description="Nội dung tinh gọn, nhiều thực hành và luôn có bước tiếp theo rõ ràng." action={<Link className="text-link" to="/courses">Xem tất cả <ArrowRight size={15} /></Link>} /><div className="landing-course-grid">{courses.map((course) => <Link to="/courses" className="landing-course-card" key={course.title}><div className="landing-course-art" style={{ background: course.color }}><span className="course-art-kanji">{course.icon}</span><span className="course-art-dots" /><span className="course-art-line" /></div><div className="landing-course-body"><div className="course-meta"><Badge tone="neutral">{course.level}</Badge><span>{course.lessons}</span></div><h3>{course.title}</h3><p>{course.subtitle}</p><span className="course-link">Xem khóa học <ArrowRight size={15} /></span></div></Link>)}</div></section>

    <section className="landing-section method-section"><div className="method-panel"><div className="method-copy"><span className="eyebrow eyebrow-light">CÁCH HANLEARN HOẠT ĐỘNG</span><h2>15 phút mỗi ngày.<br />Tiến bộ thật mỗi tuần.</h2><p>HanLearn chia nhỏ hành trình thành những phiên học vừa sức, giúp bạn duy trì động lực và biến tiếng Trung thành thói quen.</p><Link className="button button-light button-md" to="/register">Tạo lộ trình của tôi <ArrowRight size={16} /></Link></div><div className="method-steps"><div className="method-step"><span>1</span><div><strong>Chọn mục tiêu</strong><p>Du lịch, công việc, HSK hay giao tiếp.</p></div></div><div className="method-step"><span>2</span><div><strong>Học theo ngữ cảnh</strong><p>Từ vựng sống động qua bài nghe và hội thoại.</p></div></div><div className="method-step"><span>3</span><div><strong>Ôn tập đúng lúc</strong><p>SRS nhắc bạn ôn trước khi quên.</p></div></div></div></div></section>

    <section className="landing-section testimonial-section"><SectionHeading eyebrow="CÂU CHUYỆN NGƯỜI HỌC" title="Học đều, thấy khác" /><div className="testimonial-grid"><Card className="testimonial-card"><Quote size={23} className="quote-icon" /><p>“Mình từng bỏ cuộc với pinyin vài lần. HanLearn làm mọi thứ rõ ràng hơn, mỗi ngày chỉ cần 15 phút nhưng sau một tháng mình đã nghe hiểu được hội thoại cơ bản.”</p><div className="testimonial-person"><span className="avatar avatar-green">MA</span><div><strong>Mai Anh</strong><small>Học viên HSK 2</small></div><span className="rating">★★★★★</span></div></Card><Card className="testimonial-card testimonial-highlight"><div className="testimonial-highlight-mark">✦</div><p>“Điều mình thích nhất là luôn biết mình đang ở đâu và cần làm gì tiếp theo.”</p><div className="testimonial-person"><span className="avatar avatar-purple">TL</span><div><strong>Tuấn Long</strong><small>Học viên HSK 3</small></div><span className="rating">★★★★★</span></div></Card></div></section>

    <section className="landing-cta"><div><span className="eyebrow eyebrow-light">SẴN SÀNG BẮT ĐẦU?</span><h2>Một phiên học nhỏ.<br />Một bước tiến lớn.</h2><p>Tham gia HanLearn và bắt đầu nói tiếng Trung tự tin hơn từ hôm nay.</p></div><Link className="button button-light button-lg" to="/register">Học miễn phí ngay <ArrowRight size={18} /></Link></section>
  </main><footer className="public-footer"><Brand /><span>© 2025 HanLearn. Học tiếng Trung theo cách của bạn.</span><div><a href="#skills">Về HanLearn</a><a href="#courses">Khóa học</a><a href="#faq">Trợ giúp</a></div></footer></div>;
}
