import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowLeft, ArrowRight, Check, ChevronDown, Download, FileText, Headphones, Lightbulb, Mic2, PenLine, Play, Quote, RotateCcw, Volume2 } from 'lucide-react';
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { useEffect, useState } from 'react';
import { apiGet, apiPost } from '../api/client';
import { ErrorState, PageSkeleton } from '../components/states';
import { Badge, Button, Card } from '../components/ui';
import type { LessonDetail } from '../types';

export function LessonPage() {
  const { id = '' } = useParams();
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const requestedSection = lessonSectionFromQuery(searchParams.get('section'));
  const queryClient = useQueryClient();
  const query = useQuery({ queryKey: ['lesson', id], queryFn: () => apiGet<LessonDetail>(`/courses/lessons/${id}`) });
  const complete = useMutation({ mutationFn: () => apiPost(`/courses/lessons/${id}/complete`), onSuccess: () => { void queryClient.invalidateQueries({ queryKey: ['lesson', id] }); void queryClient.invalidateQueries({ queryKey: ['dashboard'] }); } });
  const [section, setSection] = useState(requestedSection);
  useEffect(() => { setSection(requestedSection); }, [id, requestedSection]);
  const [pinyinVisible, setPinyinVisible] = useState(true);
  const [translationVisible, setTranslationVisible] = useState(true);
  if (query.isLoading) return <PageSkeleton />;
  if (query.isError || !query.data) return <ErrorState message="Không thể mở bài học này." retry={() => void query.refetch()} />;
  const lesson = query.data;
  const tabs = [{ label: 'Khởi động', icon: Play }, { label: 'Nội dung', icon: FileText }, { label: 'Từ vựng', icon: Volume2 }, { label: 'Nghe', icon: Headphones }, { label: 'Nói', icon: Mic2 }, { label: 'Đọc', icon: '阅' }, { label: 'Viết', icon: PenLine }];
  return <div className="lesson-player"><header className="lesson-topbar"><Link to={`/courses/${lesson.module.course.slug}`} className="lesson-back"><ArrowLeft size={17} /> <span>Quay lại khóa học</span></Link><div className="lesson-context"><span>{lesson.module.course.title}</span><strong>{lesson.title}</strong></div><div className="lesson-top-actions"><span className="lesson-streak">🔥 12</span><button className="icon-button" aria-label="Đóng bài học" onClick={() => navigate(`/courses/${lesson.module.course.slug}`)}>×</button></div></header><div className="lesson-progress">{tabs.map((tab, index) => <span key={tab.label} className={section >= index ? 'active' : ''} />)}</div><div className="lesson-body"><aside className="lesson-outline"><span className="card-overline">NỘI DUNG BÀI HỌC</span>{tabs.map(({ label, icon: Icon }, index) => <button key={label} className={section === index ? 'active' : ''} onClick={() => setSection(index)}><span className="outline-number">{index + 1}</span>{typeof Icon === 'string' ? <span className="outline-icon hanzi-symbol">{Icon}</span> : <Icon size={16} />}<span>{label}</span>{section > index && <Check size={14} className="outline-done" />}</button>)}</aside><main className="lesson-content"><div className="lesson-content-heading"><Badge tone="red">BÀI {lesson.sortOrder.toString().padStart(2, '0')}</Badge><span>{lesson.durationMinutes} phút học</span></div>{section === 0 && <IntroSection lesson={lesson} onStart={() => setSection(1)} />}{section === 1 && <ContentBlocksSection lesson={lesson} />}{section === 2 && <VocabularySection lesson={lesson} pinyinVisible={pinyinVisible} translationVisible={translationVisible} setPinyinVisible={setPinyinVisible} setTranslationVisible={setTranslationVisible} />}{section === 3 && <ListeningSection lesson={lesson} />}{section === 4 && <SpeakingSection lesson={lesson} />}{section === 5 && <ReadingSection lesson={lesson} />}{section === 6 && <WritingSection lesson={lesson} />}</main></div><footer className="lesson-footer"><Button variant="ghost" disabled={section === 0} onClick={() => setSection(Math.max(0, section - 1))}><ArrowLeft size={16} /> Trước</Button><span><strong>{section + 1}</strong> / {tabs.length}</span>{section < tabs.length - 1 ? <Button variant="primary" onClick={() => setSection(section + 1)}>Tiếp tục <ArrowRight size={16} /></Button> : <Button variant="primary" onClick={() => complete.mutate()} loading={complete.isPending}>{complete.isSuccess ? 'Đã hoàn thành' : 'Hoàn thành bài'} <Check size={16} /></Button>}</footer></div>;
}

function lessonSectionFromQuery(value: string | null) {
  const section = Number(value);
  return Number.isInteger(section) && section >= 0 && section <= 6 ? section : 0;
}

function IntroSection({ lesson, onStart }: { lesson: LessonDetail; onStart: () => void }) { return <div className="lesson-intro"><span className="lesson-hero-icon">中</span><h1>{lesson.title}</h1><p>{lesson.summary}</p><div className="intro-objectives"><div><Check size={16} /><span>Học từ vựng trọng tâm</span></div><div><Check size={16} /><span>Luyện nghe và phát âm</span></div><div><Check size={16} /><span>Ôn tập bằng bài kiểm tra ngắn</span></div></div><Button size="lg" onClick={onStart}>Bắt đầu học <ArrowRight size={17} /></Button></div>; }

function ContentBlocksSection({ lesson }: { lesson: LessonDetail }) { return <div className="lesson-section lesson-content-blocks"><span className="eyebrow">NỘI DUNG BÀI HỌC</span><h1>Học qua nhiều định dạng</h1><p className="section-lead">Đọc, xem, nghe và tải tài liệu theo nhịp học của bạn.</p>{lesson.contentBlocks.length ? <div className="lesson-block-stack">{lesson.contentBlocks.map((block) => <LessonContentBlockView key={block.id} block={block} />)}</div> : <EmptyLesson title="Nội dung bài học đang được cập nhật" />}</div>; }

function LessonContentBlockView({ block }: { block: LessonDetail['contentBlocks'][number] }) {
  const title = block.title && <h2>{block.title}</h2>;
  const caption = block.caption && <small className="lesson-media-caption">{block.caption}</small>;
  if (block.type === 'DIVIDER') return <div className="lesson-content-divider" aria-hidden="true" />;
  if (block.type === 'TEXT') return <article className="lesson-text-block">{title}<div className="lesson-rich-text">{block.body}</div></article>;
  if (block.type === 'CALLOUT') return <aside className="lesson-callout"><Quote size={18} /> <div>{title}<p>{block.body}</p></div></aside>;
  if (block.type === 'IMAGE' && block.assetUrl) return <figure className="lesson-media-block">{title}<img src={block.assetUrl} alt={block.altText || block.title || 'Hình ảnh bài học'} loading="lazy" />{caption}</figure>;
  if (block.type === 'VIDEO' && block.assetUrl) return <figure className="lesson-media-block">{title}<LessonVideo block={block} />{caption}</figure>;
  if (block.type === 'AUDIO' && block.assetUrl) return <article className="lesson-audio-block">{title}<audio controls preload="metadata" src={block.assetUrl}>Trình duyệt không hỗ trợ audio.</audio>{caption}</article>;
  if (block.type === 'FILE' && block.assetUrl) return <article className="lesson-file-block"><FileText size={22} /><div>{title || <strong>Tài liệu bài học</strong>}<p>{block.caption || 'Mở hoặc tải tài liệu để học thêm.'}</p><a href={block.assetUrl} target="_blank" rel="noreferrer"><Download size={15} /> Mở tài liệu</a></div></article>;
  if (block.type === 'EMBED' && block.assetUrl) return <article className="lesson-embed-block">{title}<iframe src={block.assetUrl} title={block.title || 'Nội dung nhúng'} loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen /></article>;
  return null;
}

function LessonVideo({ block }: { block: LessonDetail['contentBlocks'][number] }) { const url = block.assetUrl || ''; const youtube = url.match(/(?:youtube\.com\/(?:watch\?v=|embed\/)|youtu\.be\/)([\w-]+)/i); const vimeo = url.match(/vimeo\.com\/(\d+)/i); if (youtube || vimeo) return <iframe src={youtube ? `https://www.youtube.com/embed/${youtube[1]}` : `https://player.vimeo.com/video/${vimeo?.[1]}`} title={block.title || 'Video bài học'} loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen />; return <video controls preload="metadata" poster={block.thumbnailUrl || undefined} src={url}>Trình duyệt không hỗ trợ video.</video>; }

function VocabularySection({ lesson, pinyinVisible, translationVisible, setPinyinVisible, setTranslationVisible }: { lesson: LessonDetail; pinyinVisible: boolean; translationVisible: boolean; setPinyinVisible: (value: boolean) => void; setTranslationVisible: (value: boolean) => void }) { return <div className="lesson-section"><div className="lesson-section-title"><div><span className="eyebrow">TỪ VỰNG TRỌNG TÂM</span><h1>Những từ cần nhớ</h1></div><div className="lesson-toggles"><button className={pinyinVisible ? 'active' : ''} onClick={() => setPinyinVisible(!pinyinVisible)}>Pinyin</button><button className={translationVisible ? 'active' : ''} onClick={() => setTranslationVisible(!translationVisible)}>Dịch nghĩa</button></div></div><div className="lesson-vocab-grid">{lesson.lessonWords.map(({ vocabulary }) => <Card className="lesson-vocab-card" key={vocabulary.id}><div className="lesson-vocab-main"><strong>{vocabulary.simplified}</strong><button className="audio-round" aria-label={`Nghe ${vocabulary.simplified}`} onClick={() => speak(vocabulary.simplified)}><Volume2 size={16} /></button></div>{pinyinVisible && <span className="vocab-pinyin">{vocabulary.pinyin}</span>}{translationVisible && <span className="vocab-meaning">{vocabulary.meaningVi}</span>}<div className="vocab-divider" /><span className="vocab-example">{vocabulary.exampleCn}</span>{pinyinVisible && <small>{vocabulary.examplePy}</small>}</Card>)}</div></div>; }

function ListeningSection({ lesson }: { lesson: LessonDetail }) { const exercise = lesson.listening[0]; const [playing, setPlaying] = useState(false); const [selected, setSelected] = useState(''); if (!exercise) return <EmptyLesson title="Bài nghe đang được cập nhật" />; return <div className="lesson-section skill-exercise"><span className="eyebrow">LUYỆN NGHE</span><h1>Nghe và chọn đáp án</h1><p className="section-lead">Nghe câu hỏi, sau đó chọn câu trả lời bạn nghe được.</p><Card className="audio-exercise"><button className={`audio-big ${playing ? 'playing' : ''}`} onClick={() => { setPlaying(!playing); speak(exercise.transcript); }} aria-label="Phát audio"><Volume2 size={24} /></button><div><span className="audio-label">AUDIO · TỐC ĐỘ 1×</span><div className="audio-wave large"><i /><i /><i /><i /><i /><i /><i /><i /><i /><i /><i /><i /><i /><i /><i /></div><small>{playing ? 'Đang phát…' : 'Nhấn để nghe lại'}</small></div><button className="speed-button">1× <ChevronDown size={14} /></button></Card><div className="question-block"><span className="question-number">01</span><h2>{exercise.questions[0]?.prompt}</h2><div className="answer-options">{(exercise.questions[0]?.options ?? []).map((option, index) => <button className={selected === option ? 'selected' : ''} key={option} onClick={() => setSelected(option)}><span>{String.fromCharCode(65 + index)}</span>{option}</button>)}</div>{selected && <div className={`answer-feedback ${selected === exercise.questions[0]?.answer ? 'correct' : 'wrong'}`}>{selected === exercise.questions[0]?.answer ? <><Check size={17} /> Chính xác! Bạn nghe rất tốt.</> : <>Chưa chính xác. Hãy nghe lại và thử lần nữa.</>}</div>}</div></div>; }

function SpeakingSection({ lesson }: { lesson: LessonDetail }) { const exercise = lesson.speaking[0]; const [recording, setRecording] = useState(false); if (!exercise) return <EmptyLesson title="Bài nói đang được cập nhật" />; return <div className="lesson-section speaking-exercise"><span className="eyebrow">LUYỆN NÓI</span><h1>Nói như người bản xứ</h1><p className="section-lead">Nghe câu mẫu, sau đó thu âm giọng nói của bạn.</p><Card className="speak-prompt"><span className="prompt-label">CÂU MẪU</span><strong>{exercise.promptCn}</strong><span className="prompt-pinyin">{exercise.promptPy}</span><span className="prompt-translation">{exercise.promptVi}</span><div className="prompt-actions"><Button variant="secondary" onClick={() => speak(exercise.promptCn)}><Volume2 size={16} /> Nghe mẫu</Button><button className={`record-button ${recording ? 'recording' : ''}`} onClick={() => setRecording(!recording)}><span className="record-dot" /> {recording ? 'Đang nghe…' : 'Nhấn để nói'}</button></div></Card>{recording && <div className="speech-feedback"><span>Đang lắng nghe</span><div className="recording-bars"><i /><i /><i /><i /><i /><i /><i /></div><p>Hãy nói rõ và tự nhiên nhé</p></div>}</div>; }

function ReadingSection({ lesson }: { lesson: LessonDetail }) { const exercise = lesson.reading[0]; const [showPy, setShowPy] = useState(true); const [showVi, setShowVi] = useState(false); if (!exercise) return <EmptyLesson title="Bài đọc đang được cập nhật" />; return <div className="lesson-section"><div className="lesson-section-title"><div><span className="eyebrow">LUYỆN ĐỌC</span><h1>Đọc trong ngữ cảnh</h1></div><div className="lesson-toggles"><button className={showPy ? 'active' : ''} onClick={() => setShowPy(!showPy)}>Pinyin</button><button className={showVi ? 'active' : ''} onClick={() => setShowVi(!showVi)}>Dịch</button></div></div><Card className="reading-passage"><div className="reading-cn">{exercise.passageCn}</div>{showPy && <div className="reading-py">{exercise.passagePy}</div>}{showVi && <div className="reading-vi">{exercise.passageVi}</div>}<div className="reading-actions"><button onClick={() => speak(exercise.passageCn)}><Volume2 size={15} /> Nghe bài đọc</button><button><Lightbulb size={15} /> Mẹo đọc hiểu</button></div></Card><div className="question-block reading-question"><span className="question-number">01</span><h2>{exercise.questions[0]?.prompt}</h2><div className="answer-options compact">{exercise.questions[0]?.options.map((option) => <button key={option}>{option}</button>)}</div></div></div>; }

function WritingSection({ lesson }: { lesson: LessonDetail }) { const exercise = lesson.writing[0]; const [answer, setAnswer] = useState(''); const [checked, setChecked] = useState(false); if (!exercise) return <EmptyLesson title="Bài viết đang được cập nhật" />; return <div className="lesson-section writing-exercise"><span className="eyebrow">LUYỆN VIẾT</span><h1>Viết câu bằng tiếng Trung</h1><p className="section-lead">Sắp xếp từ và áp dụng cấu trúc vừa học.</p><Card className="writing-prompt"><span className="prompt-label">HÃY VIẾT BẰNG TIẾNG TRUNG</span><strong>{exercise.promptVi}</strong><div className="writing-input-wrap"><textarea value={answer} onChange={(event) => { setAnswer(event.target.value); setChecked(false); }} placeholder="Nhập câu trả lời của bạn…" rows={3} aria-label="Câu trả lời viết" /><span>{answer.length} ký tự</span></div><div className="writing-hint"><Lightbulb size={16} /><span>{exercise.hint}</span></div><div className="writing-actions"><Button variant="secondary" onClick={() => { setAnswer(''); setChecked(false); }}><RotateCcw size={15} /> Xóa</Button><Button onClick={() => setChecked(true)}>Kiểm tra <Check size={15} /></Button></div>{checked && <div className={`answer-feedback ${answer.trim() === exercise.expectedCn ? 'correct' : 'wrong'}`}>{answer.trim() === exercise.expectedCn ? <><Check size={17} /> Tuyệt vời! Câu của bạn chính xác.</> : <>Đáp án gợi ý: <strong>{exercise.expectedCn}</strong></>}</div>}</Card></div>; }

function EmptyLesson({ title }: { title: string }) { return <div className="empty-state"><span className="empty-icon">✦</span><h2>{title}</h2><p>Phần nội dung này sẽ sớm được cập nhật.</p></div>; }
function speak(text: string) { if ('speechSynthesis' in window) { window.speechSynthesis.cancel(); const utterance = new SpeechSynthesisUtterance(text); utterance.lang = 'zh-CN'; window.speechSynthesis.speak(utterance); } }
