import { useQuery } from '@tanstack/react-query';
import { Bell, BookOpen, Check, ChevronRight, FileText, Search, Shield, SlidersHorizontal, UserRound } from 'lucide-react';
import { useState } from 'react';
import { Link } from 'react-router-dom';
import { apiGet } from '../api/client';
import { PageHeader } from '../components/layout';
import { ErrorState, PageSkeleton } from '../components/states';
import { Badge, Button, Card, EmptyState, SectionHeading } from '../components/ui';

interface HskLevelView { id: string; code: string; name: string; description: string; vocabularyCount: number; learnedCount: number; progressPct: number; courseCount: number; exerciseCount: number }

export function HskPage() { const query = useQuery({ queryKey: ['hsk'], queryFn: () => apiGet<HskLevelView[]>('/hsk') }); return <div className="page-stack hsk-page"><PageHeader eyebrow="LUYỆN THI HSK" title="Chọn cấp độ, chinh phục mục tiêu" description="Lộ trình theo chuẩn HSK với dữ liệu từ vựng và bài luyện thật trong hệ thống." action={<Badge tone="purple">HSK 1 → HSK 6</Badge>} />{query.isLoading ? <PageSkeleton /> : query.isError ? <ErrorState retry={() => void query.refetch()} /> : <div className="hsk-grid">{query.data?.map((level, index) => <Card className={`hsk-card hsk-${index + 1}`} key={level.id}><div className="hsk-card-top"><span className="hsk-number">{String(index + 1).padStart(2, '0')}</span><Badge tone={index < 2 ? 'red' : index < 4 ? 'orange' : 'purple'}>{level.name}</Badge></div><h2>{level.name}</h2><p>{level.description}</p><div className="hsk-metrics"><span><BookOpen size={14} /> {level.vocabularyCount.toLocaleString('vi-VN')} từ</span><span><Shield size={14} /> {level.exerciseCount} bài luyện</span></div><div className="hsk-progress"><div><span>Đã học {level.learnedCount}/{level.vocabularyCount}</span><strong>{level.progressPct}%</strong></div><div className="progress-track"><span style={{ width: `${level.progressPct}%` }} /></div></div><Link to={`/hsk/${level.code}`} className="text-link">Xem lộ trình <ArrowRightIcon /></Link></Card>)}</div>}</div>; }
function ArrowRightIcon() { return <span>→</span>; }

export function NotebookPage() { const [notes, setNotes] = useState([{ title: 'Cấu trúc 因为...所以...', content: 'Dùng để nói nguyên nhân và kết quả.', date: 'Hôm nay' }, { title: 'Từ vựng nhà hàng', content: '菜单 · 服务员 · 好吃 · 买单', date: 'Hôm qua' }]); const [title, setTitle] = useState(''); const [content, setContent] = useState(''); return <div className="page-stack notebook-page"><PageHeader eyebrow="SỔ TAY HỌC TẬP" title="Ghi lại điều đáng nhớ" description="Tạo ghi chú cá nhân cho từ vựng, ngữ pháp và những điều bạn muốn xem lại." action={<Button onClick={() => { if (title.trim()) { setNotes([{ title, content, date: 'Vừa xong' }, ...notes]); setTitle(''); setContent(''); } }}><FileText size={16} /> Tạo ghi chú</Button>} /><div className="notebook-layout"><Card className="note-editor"><div className="card-overline">GHI CHÚ MỚI</div><input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Tiêu đề ghi chú" /><textarea value={content} onChange={(event) => setContent(event.target.value)} placeholder="Viết điều bạn muốn ghi nhớ…" rows={10} /><div className="note-editor-footer"><span>{content.length} ký tự</span><Button variant="secondary" size="sm" onClick={() => { setTitle(''); setContent(''); }}>Xóa</Button></div></Card><div className="notes-list"><div className="notes-list-heading"><h2>Ghi chú gần đây</h2><span>{notes.length} ghi chú</span></div>{notes.map((note) => <Card className="note-card" key={`${note.title}-${note.date}`}><div className="note-card-top"><span className="note-pin">●</span><small>{note.date}</small><button className="icon-button"><SlidersHorizontal size={16} /></button></div><h3>{note.title}</h3><p>{note.content}</p><Link className="text-link" to="/notebook">Mở ghi chú <ChevronRight size={14} /></Link></Card>)}</div></div></div>; }

export function SettingsPage() { return <div className="page-stack settings-page"><PageHeader eyebrow="CÀI ĐẶT" title="Không gian học của bạn" description="Tùy chỉnh trải nghiệm để việc học trở nên dễ chịu và hiệu quả hơn." /><div className="settings-layout"><Card className="settings-nav"><button className="active"><UserRound size={17} /> Hồ sơ cá nhân</button><button><Bell size={17} /> Thông báo</button><button><SlidersHorizontal size={17} /> Tùy chọn học tập</button><button><Shield size={17} /> Bảo mật</button></Card><Card className="settings-content"><div className="settings-section"><div><h2>Hồ sơ cá nhân</h2><p>Thông tin này giúp HanLearn cá nhân hóa lộ trình của bạn.</p></div><div className="settings-avatar-row"><span className="profile-avatar small">Q</span><Button variant="secondary" size="sm">Đổi ảnh đại diện</Button></div><label>Tên hiển thị<input defaultValue="Quyến" /></label><label>Email<input defaultValue="student@hanlearn.local" disabled /></label><label>Mục tiêu học tập<select defaultValue="Giao tiếp"><option>Giao tiếp</option><option>HSK</option><option>Du lịch</option><option>Công việc</option></select></label><Button>Lưu thay đổi <Check size={15} /></Button></div><div className="settings-section"><div><h2>Giao diện</h2><p>Chọn chế độ hiển thị phù hợp với mắt của bạn.</p></div><div className="theme-options"><button className="active"><span className="theme-preview light-preview" />Sáng</button><button><span className="theme-preview dark-preview" />Tối</button><button><span className="theme-preview system-preview" />Theo hệ thống</button></div></div></Card></div></div>; }

export function NotificationsPage() { const query = useQuery({ queryKey: ['notifications'], queryFn: async () => [{ title: 'Bạn có 20 từ cần ôn hôm nay', body: 'Dành 5 phút để giữ vững streak 12 ngày nhé.', type: 'review', time: '10 phút trước' }, { title: 'Bạn vừa đạt Achievement', body: 'Chúc mừng! Bạn đã duy trì chuỗi học 7 ngày.', type: 'achievement', time: 'Hôm qua' }] }); return <div className="page-stack"><PageHeader eyebrow="THÔNG BÁO" title="Cập nhật học tập" description="Những điều HanLearn muốn nhắc bạn hôm nay." />{query.isLoading ? <PageSkeleton /> : <Card className="notification-list">{query.data?.map((notification) => <div className="notification-row" key={notification.title}><span className={`notification-icon ${notification.type}`}>{notification.type === 'review' ? '↻' : '✦'}</span><div><strong>{notification.title}</strong><p>{notification.body}</p><small>{notification.time}</small></div><ChevronRight size={17} /></div>)}</Card>}</div>; }

export function SearchPage() { const [search, setSearch] = useState(''); return <div className="page-stack search-page"><PageHeader eyebrow="TÌM KIẾM NHANH" title="Tìm điều bạn muốn học" description="Tìm bằng chữ Hán, pinyin, tiếng Việt hoặc tên bài học." /><Card className="global-search-panel"><Search size={22} /><input autoFocus value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Ví dụ: 你好, ni hao, xin chào…" /><kbd>ESC</kbd></Card>{search ? <div className="search-results"><SectionHeading eyebrow="KẾT QUẢ GỢI Ý" title={`Kết quả cho “${search}”`} /><Card className="search-result-row"><span className="search-result-symbol">你</span><div><Badge tone="red">Từ vựng · HSK 1</Badge><h3>你好 · nǐ hǎo</h3><p>Xin chào</p></div><ChevronRight size={17} /></Card></div> : <EmptyState icon="⌕" title="Bắt đầu tìm kiếm" description="Nhấn Ctrl + K bất cứ lúc nào để mở tìm kiếm nhanh." />}</div>; }
